### ISSUE TITLE
Document end-user use cases on how to do core functions

### ISSUE THREAD

**Issue by davidwesst** [cocobokostudios/videogamelibrary#41]
Record videos or screenshots doing specific end user functions, specifically:

- [ ] Adding a game to a collection (#36)
- [ ] Removing a game from a collection (#38)
- [ ] Editing game data (#11)
- [ ] Displaying a different saved collection

**Idea** This could be as simple as a tutorial video walking through "how to use the application" for the 0.2 release.
